apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-huggingface
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpt-hf-pod
  template:
    metadata:
      labels:
        app: gpt-hf-pod
    spec:
      containers:
        - name: gpt-container
          image: docker tag fastapi-app:latest pandayip97/fastapi-app:latest        # Replace with your Docker image, e.g., fastapi-app:latest
          ports:
            - containerPort: 8000
