apiVersion: v1
kind: Service
metadata:
  name: gpt-hf-service
spec:
  type: NodePort
  selector:
    app: gpt-hf-pod
  ports:
    - port: 8000       # Service port
      targetPort: 8000 # Container port
      nodePort: 30007  # NodePort for external access
